### ISSUE TITLE
medium article

### ISSUE THREAD

**Issue by ipatch** [ajmalsiddiqui/dotfiles#1]
Hey dude,

Just read your medium article,

[Dive into Dotfiles -- Part 1](https://medium.com/@ajmalsiddiqui21/dive-into-dotfiles-part-1-e4eb1003cff6)

Took a look 🙈 at your dotfiles, and after grazing 🐄 through your medium article two things that you might find interesting.

1. In GitHub flavor markdown syntax one can you a `##` to create a heading, which I'm sure you probably already know that, but GitHub CSS styles apply a nice thin `<hr>` as opposed to the thick lines used by using `---` in markdown.

2. If you're getting your feet wet with `git` I'd highly recommend setting up a `$USER` specific `~/.gitconfig` file so you can offload your git aliases you put in your `.bash_profile` file, thus making your setup shell agnostic.

If you what to check out an example of a `.gitconfig` ***shamless plug 💁🏻‍♂️*** I have mine setup [here](https://github.com/ipatch/dotfiles/blob/master/config/git/gitconfig)

H@ppy H@ck!ng

**Comment by ajmalsiddiqui** [comment]
Hey man,

Thanks a ton for reading my stuff and taking the time out to check my dotfiles. 

1. I should give this a shot I guess. Thanks a lot for the tip!

2. That is a brilliant suggestion that I should have implemented a long time ago. It's been a while since I played with my dotfiles, and this is the first thing I'll do once I get to it. Thanks a ton!

P.S. Your dotfiles look like they can teach me a thing or two. I'll check em out in detail. Lemme know if there's anything else you'd like to point out. 

Cheers!

**Comment by ipatch** [comment]
Yeah man, having a well crafted dotfiles repo is like trimming a bonsai tree ⽊, it's definitely an art.  If I can think of anything else off the top of my head, I'll try and bring it up.

**Comment by ajmalsiddiqui** [comment]
I've changed my `README.md` to use `##` for headings and offloaded my git aliases to a `.gitconfig` file. I admit that my `.gitconfig` needs work but the pointers given in this issue have been implemented. Hence, I'm closing the issue.

Thanks a lot for taking out the time and suggesting those changes!
